# Go
# Build your Go project.
# Add steps that test, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/go

trigger:
  batch: true
  branches:
    include:
    - master

pr: none

jobs:
- job: build
  timeoutInMinutes: 60

  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  - task: GoTool@0
    inputs:
      version: '1.12'
  - script: |
      go version
      go get -v -t -d ./...
      if [ -f Gopkg.toml ]; then
          curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
          dep ensure
      fi
      
    workingDirectory: '$(system.defaultWorkingDirectory)'
    displayName: 'Get dependencies'

  - script: |
      make build-linux64
    workingDirectory: '$(system.defaultWorkingDirectory)'
    displayName: 'Build for Linux 64'

  - script: |
      make build-linux32
    workingDirectory: '$(system.defaultWorkingDirectory)'
    displayName: 'Build for Linux 32'

  - script: |
      make build-windows64
    workingDirectory: '$(system.defaultWorkingDirectory)'
    displayName: 'Build for Windows 64'

  - script: |
      make build-windows32
    workingDirectory: '$(system.defaultWorkingDirectory)'
    displayName: 'Build for Windows 32'

  - script: |
      make build-osx64
    workingDirectory: '$(system.defaultWorkingDirectory)'
    displayName: 'Build for OSX 64'

  - script: |
      make build-osx32
    workingDirectory: '$(system.defaultWorkingDirectory)'
    displayName: 'Build for OSX 32'

  - script: |
      make test
    workingDirectory: '$(system.defaultWorkingDirectory)'
    displayName: 'Test'

  - script: |
      bash <(curl -s https://codecov.io/bash) -t 3d625ec9-4ce0-40a8-97c4-af45c5930521
    workingDirectory: '$(system.defaultWorkingDirectory)'
    displayName: 'Upload Codecov'
